version: '3'

networks:
    my-network:
        driver: bridge

volumes:
  postgres_data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 8080:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - my-network
    command: bash -c "sleep 10; rabbitmq-server;"

  my-app:
    build: .
    container_name: my-app
    restart: always
    networks:
        - my-network
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  listener:
    build: .
    command: sh -c "
      sleep 20 &&
      python listener.py"
    restart: always
    networks:
        - my-network
    depends_on:
        - rabbitmq
        - my-app

  postgres:
    image: postgres:13.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5444:5432"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 250M
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network
